2019-09-17 18:33:16,553 [main] DEBUG util.Shell (Shell.java:<clinit>(506)) - Failed to detect a valid hadoop home directory
java.io.FileNotFoundException: Hadoop home directory c:\depot\adls-migrator\..\..\hadoop-common-project\hadoop-common\target does not exist
	at org.apache.hadoop.util.Shell.checkHadoopHomeInner(Shell.java:477)
	at org.apache.hadoop.util.Shell.checkHadoopHome(Shell.java:425)
	at org.apache.hadoop.util.Shell.<clinit>(Shell.java:502)
	at org.apache.hadoop.util.StringUtils.<clinit>(StringUtils.java:78)
	at org.apache.hadoop.fs.FileSystem$Cache$Key.<init>(FileSystem.java:3421)
	at org.apache.hadoop.fs.FileSystem$Cache$Key.<init>(FileSystem.java:3416)
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:3258)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:470)
	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:356)
	at com.azure.storage.adlsmigrator.mapred.RetriableFileCopyCommand.getInputStream(RetriableFileCopyCommand.java:323)
	at com.azure.storage.adlsmigrator.mapred.RetriableFileCopyCommand.copyBytes(RetriableFileCopyCommand.java:259)
	at com.azure.storage.adlsmigrator.mapred.TestRetriableFileCopyCommand.testFailOnCloseError(TestRetriableFileCopyCommand.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:379)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:340)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:413)
2019-09-17 18:33:16,559 [main] WARN  util.Shell (Shell.java:<clinit>(679)) - Did not find winutils.exe: {}
java.io.FileNotFoundException: java.io.FileNotFoundException: Hadoop home directory c:\depot\adls-migrator\..\..\hadoop-common-project\hadoop-common\target does not exist -see https://wiki.apache.org/hadoop/WindowsProblems
	at org.apache.hadoop.util.Shell.fileNotFoundException(Shell.java:534)
	at org.apache.hadoop.util.Shell.getHadoopHomeDir(Shell.java:555)
	at org.apache.hadoop.util.Shell.getQualifiedBin(Shell.java:578)
	at org.apache.hadoop.util.Shell.<clinit>(Shell.java:675)
	at org.apache.hadoop.util.StringUtils.<clinit>(StringUtils.java:78)
	at org.apache.hadoop.fs.FileSystem$Cache$Key.<init>(FileSystem.java:3421)
	at org.apache.hadoop.fs.FileSystem$Cache$Key.<init>(FileSystem.java:3416)
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:3258)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:470)
	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:356)
	at com.azure.storage.adlsmigrator.mapred.RetriableFileCopyCommand.getInputStream(RetriableFileCopyCommand.java:323)
	at com.azure.storage.adlsmigrator.mapred.RetriableFileCopyCommand.copyBytes(RetriableFileCopyCommand.java:259)
	at com.azure.storage.adlsmigrator.mapred.TestRetriableFileCopyCommand.testFailOnCloseError(TestRetriableFileCopyCommand.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:379)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:340)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:413)
Caused by: java.io.FileNotFoundException: Hadoop home directory c:\depot\adls-migrator\..\..\hadoop-common-project\hadoop-common\target does not exist
	at org.apache.hadoop.util.Shell.checkHadoopHomeInner(Shell.java:477)
	at org.apache.hadoop.util.Shell.checkHadoopHome(Shell.java:425)
	at org.apache.hadoop.util.Shell.<clinit>(Shell.java:502)
	... 34 more
2019-09-17 18:33:16,560 [main] DEBUG util.Shell (Shell.java:<clinit>(681)) - Failed to find winutils.exe
java.io.FileNotFoundException: java.io.FileNotFoundException: Hadoop home directory c:\depot\adls-migrator\..\..\hadoop-common-project\hadoop-common\target does not exist -see https://wiki.apache.org/hadoop/WindowsProblems
	at org.apache.hadoop.util.Shell.fileNotFoundException(Shell.java:534)
	at org.apache.hadoop.util.Shell.getHadoopHomeDir(Shell.java:555)
	at org.apache.hadoop.util.Shell.getQualifiedBin(Shell.java:578)
	at org.apache.hadoop.util.Shell.<clinit>(Shell.java:675)
	at org.apache.hadoop.util.StringUtils.<clinit>(StringUtils.java:78)
	at org.apache.hadoop.fs.FileSystem$Cache$Key.<init>(FileSystem.java:3421)
	at org.apache.hadoop.fs.FileSystem$Cache$Key.<init>(FileSystem.java:3416)
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:3258)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:470)
	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:356)
	at com.azure.storage.adlsmigrator.mapred.RetriableFileCopyCommand.getInputStream(RetriableFileCopyCommand.java:323)
	at com.azure.storage.adlsmigrator.mapred.RetriableFileCopyCommand.copyBytes(RetriableFileCopyCommand.java:259)
	at com.azure.storage.adlsmigrator.mapred.TestRetriableFileCopyCommand.testFailOnCloseError(TestRetriableFileCopyCommand.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:379)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:340)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:413)
Caused by: java.io.FileNotFoundException: Hadoop home directory c:\depot\adls-migrator\..\..\hadoop-common-project\hadoop-common\target does not exist
	at org.apache.hadoop.util.Shell.checkHadoopHomeInner(Shell.java:477)
	at org.apache.hadoop.util.Shell.checkHadoopHome(Shell.java:425)
	at org.apache.hadoop.util.Shell.<clinit>(Shell.java:502)
	... 34 more
2019-09-17 18:33:16,598 [main] DEBUG lib.MutableMetricsFactory (MutableMetricsFactory.java:newForField(43)) - field org.apache.hadoop.metrics2.lib.MutableRate org.apache.hadoop.security.UserGroupInformation$UgiMetrics.loginSuccess with annotation @org.apache.hadoop.metrics2.annotation.Metric(always=false, sampleName=Ops, valueName=Time, about=, interval=10, type=DEFAULT, value=[Rate of successful kerberos logins and latency (milliseconds)])
2019-09-17 18:33:16,607 [main] DEBUG lib.MutableMetricsFactory (MutableMetricsFactory.java:newForField(43)) - field org.apache.hadoop.metrics2.lib.MutableRate org.apache.hadoop.security.UserGroupInformation$UgiMetrics.loginFailure with annotation @org.apache.hadoop.metrics2.annotation.Metric(always=false, sampleName=Ops, valueName=Time, about=, interval=10, type=DEFAULT, value=[Rate of failed kerberos logins and latency (milliseconds)])
2019-09-17 18:33:16,607 [main] DEBUG lib.MutableMetricsFactory (MutableMetricsFactory.java:newForField(43)) - field org.apache.hadoop.metrics2.lib.MutableRate org.apache.hadoop.security.UserGroupInformation$UgiMetrics.getGroups with annotation @org.apache.hadoop.metrics2.annotation.Metric(always=false, sampleName=Ops, valueName=Time, about=, interval=10, type=DEFAULT, value=[GetGroups])
2019-09-17 18:33:16,607 [main] DEBUG lib.MutableMetricsFactory (MutableMetricsFactory.java:newForField(43)) - field private org.apache.hadoop.metrics2.lib.MutableGaugeLong org.apache.hadoop.security.UserGroupInformation$UgiMetrics.renewalFailuresTotal with annotation @org.apache.hadoop.metrics2.annotation.Metric(always=false, sampleName=Ops, valueName=Time, about=, interval=10, type=DEFAULT, value=[Renewal failures since startup])
2019-09-17 18:33:16,609 [main] DEBUG lib.MutableMetricsFactory (MutableMetricsFactory.java:newForField(43)) - field private org.apache.hadoop.metrics2.lib.MutableGaugeInt org.apache.hadoop.security.UserGroupInformation$UgiMetrics.renewalFailures with annotation @org.apache.hadoop.metrics2.annotation.Metric(always=false, sampleName=Ops, valueName=Time, about=, interval=10, type=DEFAULT, value=[Renewal failures since last successful login])
2019-09-17 18:33:16,609 [main] DEBUG impl.MetricsSystemImpl (MetricsSystemImpl.java:register(231)) - UgiMetrics, User and group related metrics
2019-09-17 18:33:16,626 [main] DEBUG security.SecurityUtil (SecurityUtil.java:setTokenServiceUseIp(121)) - Setting hadoop.security.token.service.use_ip to true
2019-09-17 18:33:16,647 [main] DEBUG security.Groups (Groups.java:getUserToGroupsMappingService(447)) -  Creating new Groups object
2019-09-17 18:33:16,653 [main] DEBUG util.NativeCodeLoader (NativeCodeLoader.java:<clinit>(46)) - Trying to load the custom-built native-hadoop library...
2019-09-17 18:33:16,656 [main] DEBUG util.NativeCodeLoader (NativeCodeLoader.java:<clinit>(55)) - Failed to load native-hadoop with error: java.lang.UnsatisfiedLinkError: no hadoop in java.library.path
2019-09-17 18:33:16,657 [main] DEBUG util.NativeCodeLoader (NativeCodeLoader.java:<clinit>(56)) - java.library.path=c:\Program Files\Java\jdk1.8.0_221\jre\bin;C:\Windows\Sun\Java\bin;C:\Windows\system32;C:\Windows;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files\Git\cmd;C:\Program Files (x86)\Windows Kits\8.0\Windows Performance Toolkit\;C:\Users\jamesbak\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Ubuntu;C:\Users\jamesbak\AppData\Local\Programs\Fiddler;C:\Users\jamesbak\AppData\Local\Programs\Microsoft VS Code\bin;C:\Program Files\Java\jdk1.8.0_221\bin;C:\Program Files\Java\apache-maven-3.6.2\bin;C:\Program Files\Java\protoc-2.5.0;;c:\depot\adls-migrator/../../hadoop-common-project/hadoop-common/target/bin;${openssl.lib};.
2019-09-17 18:33:16,657 [main] WARN  util.NativeCodeLoader (NativeCodeLoader.java:<clinit>(62)) - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
2019-09-17 18:33:16,658 [main] DEBUG util.PerformanceAdvisory (JniBasedUnixGroupsMappingWithFallback.java:<init>(41)) - Falling back to shell based
2019-09-17 18:33:16,662 [main] DEBUG security.JniBasedUnixGroupsMappingWithFallback (JniBasedUnixGroupsMappingWithFallback.java:<init>(45)) - Group mapping impl=org.apache.hadoop.security.ShellBasedUnixGroupsMapping
2019-09-17 18:33:16,820 [main] DEBUG security.Groups (Groups.java:<init>(151)) - Group mapping impl=org.apache.hadoop.security.JniBasedUnixGroupsMappingWithFallback; cacheTimeout=300000; warningDeltaMs=5000
2019-09-17 18:33:16,835 [main] DEBUG security.UserGroupInformation (UserGroupInformation.java:login(246)) - hadoop login
2019-09-17 18:33:16,851 [main] DEBUG security.UserGroupInformation (UserGroupInformation.java:commit(181)) - hadoop login commit
2019-09-17 18:33:16,867 [main] DEBUG security.UserGroupInformation (UserGroupInformation.java:commit(211)) - using local user:NTUserPrincipal: jamesbak
2019-09-17 18:33:16,867 [main] DEBUG security.UserGroupInformation (UserGroupInformation.java:commit(217)) - Using user: "NTUserPrincipal: jamesbak" with name jamesbak
2019-09-17 18:33:16,867 [main] DEBUG security.UserGroupInformation (UserGroupInformation.java:commit(227)) - User entry: "jamesbak"
2019-09-17 18:33:16,867 [main] DEBUG security.UserGroupInformation (UserGroupInformation.java:loginUserFromSubject(863)) - Assuming keytab is managed externally since logged in from subject.
